### PR TITLE
Update web library

### PR DESCRIPTION
**Pull request by rasmusjp**
-  Multi-target .Net Core 3.1 and .Net 5.0
- Add Preview Support
- Make configuration interface lighter / easier to use, now the only thing needed is to add the project alias to app settings and call `services.AddUmbracoHeartcore()` and `app.UseUmbracoHeartcoreRouting()`

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews();

    // Add Umbraco Heartcore.
    services.AddUmbracoHeartcore(options => {
        // register all strongly typed models from the current assembly.
        options.AddModels(GetType().Assembly);
    });       
}

public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
...
    app.UseAuthorization();

    // Enable Heartcore routing,
    app.UseUmbracoHeartcoreRouting();

    app.UseEndpoints(endpoints =>
...
}
```

Preview support can be enabled by configuring the ApiKey and a Secret app settings, and calling `.AddPreview()` on the `UmbraceHeartcoreBuilder` e.g

```csharp
public void ConfigureServices(IServiceCollection services)
{
...
    // Add Umbraco Heartcore.
    services.AddUmbracoHeartcore()
        .AddPreview();
}
```

Then to enter preview mod visit `/api/preview?secret={configured secret}&slug={url of page to preview}` to exit preview mode visit `/api/preview/exit`

### CODE REVIEW

**Comment by sitereactor** [comment]
> Then to enter preview mod visit /api/preview?secret={configured secret}&slug={url of page to preview} to exit preview mode visit /api/preview/exit

Is the "configured secret" part an API Key for accessing the Preview API or something else?

**Comment by rasmusjp** [comment]
Sorry,I should have specified that it can be whatever, so it will most likely be a random string that is shared between the web app and added to the url when adding preview configuration in Umbraco. It's used as extra validation so not everyone can enter preview mode.

**Comment by sitereactor** [comment]
Where or how should it be configured server side?
I would have expected some kind of property for `AddPreview()`, but maybe I overlooked something?

**Comment by rasmusjp** [comment]
It's an AppSetting so it can be set in https://github.com/umbraco/Umbraco.Headless.Client.Net/blob/26be65bdedcb8bd2a03be9a16d6babdca4e41383/samples/Umbraco.Headless.Client.Samples.Web/Umbraco.Headless.Client.Samples.Web/appsettings.json, as en environment variable or other ways app settings can be configured.

There's also an overload to `AddPreview` (like the one for `AddUmbracoHeartcore` and there's also one for `AddManagement`) that allows you to configure the options in code if you wan't to do that instead

**Pull request merged**
